version: '3.9'

services:

 
  db:
    image: postgres
    restart: always
    ports:
      - 5646:5432
    environment:
      POSTGRES_PASSWORD: user11920
      POSTGRES_USER: shop
      POSTGRES_DB: sellshopDB

 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080