# Generated by Django 5.0.7 on 2024-07-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Blling',
            new_name='blling',
        ),
    ]
