# Generated by Django 5.0.7 on 2024-07-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleblog',
            name='brend',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='products.brand'),
        ),
    ]
