# Generated by Django 5.0.7 on 2024-07-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='tag',
            field=models.BooleanField(default=True),
        ),
    ]
