# Generated by Django 5.0.7 on 2024-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_collection',
            field=models.BooleanField(default=False),
        ),
    ]
