# Generated by Django 5.0.7 on 2024-09-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_new_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection_image',
            field=models.ImageField(default=3, upload_to='collection_image'),
            preserve_default=False,
        ),
    ]
