# Generated by Django 5.0.7 on 2024-09-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection_image',
            field=models.ImageField(blank=True, null=True, upload_to='collection_image'),
        ),
    ]
