# Generated by Django 5.0.7 on 2024-09-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='countdown_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='countdown_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='countdown_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='countdown_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='products_countdown/'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='products_countdown/'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
