# Generated by Django 5.0.7 on 2024-09-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productdetail_countdown_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
