# Generated by Django 5.0.7 on 2024-09-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productdetail_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='old_price',
            new_name='new_price',
        ),
    ]
